name: FastApi App

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.11
              uses: actions/setup-python@v1
              with:
                  python-version: 3.11
            - name: Install dependencies
              run: |
                  make install
                  python -m textblob.download_corpora
            - name: Lint with pylint
              run: |
                  make lint
            - name: Test with pytest
              run: |
                  make test
            - name: Format code
              run: |
                  make format
            - name: Build container
              run: make build
            - name: Push Container
              run: make push
              env:
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            - name: Deploy Container
              run: make deploy
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: 'us-east-1'
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            - name: Deploy Container
              run: |
                AWS_ECR_PASSWORD=$(aws ecr get-login-password --region $AWS_REGION)
                echo $AWS_ECR_PASSWORD | docker login --username AWS --password-stdin $AWS_REGISTRY_URL
                make deploy
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: 'us-east-1'
                AWS_REGISTRY_URL: 188288001838.dkr.ecr.us-east-1.amazonaws.com/wikifast:latest
                
                
                
